## Prepare GWAS data

https://cloufield.github.io/gwaslab/AssignrsID/#reference-data

In [ ]:
# eval "$(conda shell.bash hook)"
# conda init
# conda activate /work/islet_cartography_scrna/scrna_cartography_gwas
# python -m ipykernel install --user --name scrna_cartography_gwas --display-name "gwas"

In [2]:
# Path and system utilities
import os                    # Operating system interface
import sys                   # System-specific parameters and functions
import glob                  # File pattern matching
from pyhere import here      # Reproducible project paths

# dataframes
import pandas as pd
import numpy as np

# GWAS
import gwaslab as gl

sys.path.append(str(here('scripts/misc')))  # Add custom script path to system
import misc as mi

In [25]:
mi.create_directories(here("data/gwas/sumstats"))
mi.create_directories(here("data/gwas/reference"))
mi.create_directories(here("data/gwas/files"))
mi.create_directories(here("data/gwas/plots"))
mi.create_directories(here("data/gwas/ref_magma"))
mi.create_directories(here("data/gwas/sumstats_annotated"))
mi.create_directories(here("data/gwas/gs_files"))
mi.create_directories(here("data/gwas/pval_zscore"))

/work/islet_cartography_scrna/data/gwas/sumstats Directory created successfully!
/work/islet_cartography_scrna/data/gwas/reference Directory already exists!
/work/islet_cartography_scrna/data/gwas/files Directory already exists!
/work/islet_cartography_scrna/data/gwas/plots Directory already exists!
/work/islet_cartography_scrna/data/gwas/sumstats_processed Directory created successfully!
/work/islet_cartography_scrna/data/gwas/ref_magma Directory already exists!
/work/islet_cartography_scrna/data/gwas/sumstats_annotated Directory already exists!
/work/islet_cartography_scrna/data/gwas/gs_files Directory already exists!
/work/islet_cartography_scrna/data/gwas/pval_zscore Directory created successfully!

In [ ]:
# paths 
base_dir = str(here("data/gwas"))
ref_dir =  os.path.join(base_dir, "reference")
files_dir =  os.path.join(base_dir, "files")
sums_dir = os.path.join(base_dir, "sumstats")
sumsp_dir = os.path.join(base_dir, "sumstats_processed")
sumsa_dir = os.path.join(base_dir, "sumstats_annotated")

### Download reference data

In [ ]:
# hg19 (GRCh37): 
gl.download_ref("1kg_dbsnp151_hg19_auto", directory=ref_dir)
#hg38 (GRCh38): 
gl.download_ref("1kg_dbsnp151_hg38_auto", directory=ref_dir)

In [ ]:
pd.read_csv()

### Download SumStats data

- T2D GWAS was downlaoded from: https://www.diagram-consortium.org/downloads.html (access: 2025-12-19)
- Handedness was downloaded from: https://www.ebi.ac.uk/gwas/studies/GCST90013421 (access: 2025-12-19)
- Gene and reference location files were downloaded from: https://cncr.nl/research/magma/ (access: 2025-12-19)

#### Convert T2D data to correct format for magma

In [3]:
ss = gl.Sumstats("/work/islet_cartography_scrna/tmp/hair_colour.tsv.gz",  build="37", sep="\t", fmt = "ssf")

2026/01/16 13:46:36 GWASLab v4.0.3 https://cloufield.github.io/gwaslab/
2026/01/16 13:46:36 (C) 2022-2026, Yunye He, Kamatani Lab, GPL-3.0 license, gwaslab@gmail.com
2026/01/16 13:46:36 Python version: 3.12.12 | packaged by conda-forge | (main, Oct 22 2025, 23:25:55) [GCC 14.3.0]
2026/01/16 13:46:36 Start to load format from formatbook....
2026/01/16 13:46:36  -ssf format meta info:
2026/01/16 13:46:36   - format_name  : ssf
2026/01/16 13:46:36   - format_source  : https://www.biorxiv.org/content/10.1101/2022.07.15.500230v1.full
2026/01/16 13:46:36   - format_cite_name  : GWAS-SSF v0.1
2026/01/16 13:46:36   - format_separator  : \t
2026/01/16 13:46:36   - format_na  : #NA
2026/01/16 13:46:36   - format_col_order  : chromosome,base_pair_location,effect_allele,other_allele,beta,odds_ratio,hazard_ratio,standard_error,effect_allele_frequency,p_value,neg_log_10_p_value,ci_upper,ci_lower,rsid,variant_id,info,ref_allele,n
2026/01/16 13:46:36   - format_version  :  20230328
2026/01/16 13:46:36  -ssf to gwaslab format dictionary:
2026/01/16 13:46:36   - ssf keys: variant_id,rsid,chromosome,base_pair_location,other_allele,effect_allele,effect_allele_frequency,n,beta,standard_error,p_value,neg_log_10_p_value,info,odds_ratio,hazard_ratio,ci_lower,ci_upper
2026/01/16 13:46:36   - gwaslab values: SNPID,rsID,CHR,POS,NEA,EA,EAF,N,BETA,SE,P,MLOG10P,INFO,OR,HR,OR_95L,OR_95U
2026/01/16 13:46:36 Start to initialize gl.Sumstats from file :/work/islet_cartography_scrna/tmp/hair_colour.tsv.gz
2026/01/16 13:46:54  -Reading columns          : ci_upper,ci_lower,base_pair_location,standard_error,variant_id,effect_allele_frequency,odds_ratio,p_value,n,chromosome,beta,other_allele,effect_allele
2026/01/16 13:46:54  -Renaming columns to      : OR_95U,OR_95L,POS,SE,SNPID,EAF,OR,P,N,CHR,BETA,NEA,EA
2026/01/16 13:46:54  -Current Dataframe shape : 11831899  x  13
2026/01/16 13:46:55  -Initiating a status column: STATUS ...
2026/01/16 13:46:55  -Genomic coordinates are based on GRCh37/hg19...
2026/01/16 13:46:55 Start to reorder the columns ...(v4.0.3)
2026/01/16 13:46:55  -Reordering columns to    : SNPID,CHR,POS,EA,NEA,STATUS,EAF,BETA,SE,OR,OR_95U,OR_95L,P,N
2026/01/16 13:46:55 Finished reordering the columns.
2026/01/16 13:46:55  -Trying to convert datatype for CHR: string -> Int64...Success
2026/01/16 13:46:57  -Column  : SNPID  CHR   POS   EA       NEA      STATUS EAF     BETA    SE      OR      OR_95U  OR_95L  P       N
2026/01/16 13:46:57  -DType   : object Int64 int64 category category int64  float64 float64 float64 float64 float64 float64 float64 int64
2026/01/16 13:46:57  -Verified: T      T     T     T        T        T      T       T       T       T       T       T       T       T
2026/01/16 13:46:57  -Current Dataframe memory usage: 1117.09 MB
2026/01/16 13:46:57 Finished loading data successfully!

In [4]:
ss

In [22]:
ss.basic_check(verbose=False)
ss.assign_rsid(
    ref_rsid_tsv=gl.get_path("1kg_dbsnp151_hg19_auto"),
    threads=60,
    verbose=False
)

0   1   2   3   4   5   6   7   8   9   10   11   12   13   14   15

In [ ]:
# file paths
files = glob.glob(os.path.join(sums_dir, 't2d_suzuki/*v2.txt'))
def process_sumstats(file_path):
    # Extract just the filename for saving later
    base_name = os.path.basename(file_path).replace(".txt", ".pval")
    
    # Load sumstats
    ss = gl.Sumstats(
        file_path,
        build=19,
        sep="\t",
        chrom="Chromsome",
        pos="Position",
        ea="EffectAllele",
        nea="NonEffectAllele",
        eaf="EAF",
        ncontrol="Ncontrols",
        ncase="Ncases",
        beta="Beta",
        se="SE",
        p="Pval",
        verbose=False
    )
    
    ss.basic_check(verbose = False)
    
    # Assign rsIDs
    ss.assign_rsid(
        ref_rsid_tsv=gl.get_path("1kg_dbsnp151_hg19_auto"),
        threads=60, 
        verbose = False
    )
    
    # Calculate total N
    ss.data["N"] = ss.data["N_CASE"] + ss.data["N_CONTROL"]

    # Remove SNPs with no ID
    ss.data = ss.data[ss.data['rsID'].notna()]
    
    # Save
    out_file = os.path.join(sumsp_dir, base_name)
    ss.data.to_csv(out_file, sep="\t", index=False)
    
    print("Finished processing:", base_name)

# Apply to all files (like purrr::map)
processed_files = list(map(process_sumstats, files))

In [ ]:
# Path where your processed .pval files are saved
processed_path = os.path.join(sumsp_dir)  # adjust if needed

# Get all .pval files
files = glob.glob(os.path.join(processed_path, '*.pval'))

# Column rename mapping
rename_col = {'rsID': 'SNP'}

# Loop through files
for file_path in files:
    # Load file
    df = pd.read_csv(file_path, sep="\t")
    
    # Rename column
    df = df.rename(columns=rename_col)
    
    # Save back
    df.to_csv(file_path, sep="\t", index=False)
    
    print("Updated columns in:", os.path.basename(file_path))

#### Convert handedness data to correct format for magma - liftover from hg38 to hg19 (because I am missing reference from hg38)

In [ ]:
# file paths
files = glob.glob(os.path.join(sums_dir, 'handedness_cuellar/32989287-GCST90013421-EFO_0009902-Build38.f.tsv'))

def process_sumstats(file_path):
    # Extract just the filename for saving later
    base_name = os.path.basename(file_path).replace(".tsv", ".pval")
    
    # Load sumstats
    ss = gl.Sumstats(
        file_path,
        rsid = "variant_id",
        build=38,
        sep="\t",
        chrom="chromosome",
        ea="effect_allele",
        nea="other_allele",
        eaf="effect_allele_frequency",
        beta="beta",
        se="standard_error",
        p="p_value",
        z = "z",
        pos = "base_pair_location",
        OR = "odds_ratio",
        n = 1766671,
        verbose=False
    )
    
    ss.basic_check(verbose = False)

    # liftover from hg38 to hg19
    mysumstats.liftover(from_build="38", 
                    to_build="19",
                    remove=True)

    # Rename columns to use for magma
    rename_col = {'rsID': 'SNP'}
    
    # Remove SNPs with no ID
    ss.data = ss.data[ss.data['rsID'].notna()]
    ss.data = ss.data.rename(columns=rename_col)
    
    # Save
    out_file = os.path.join(sumsp_dir, base_name)
    ss.data.to_csv(out_file, sep="\t", index=False)
    
    print("Finished processing:", base_name)

# Apply to all files (like purrr::map)
processed_files = list(map(process_sumstats, files))

In [6]:
ss = gl.Sumstats(
    "/work/GCST90691576.tsv.gz",
    sep="\t",
    fmt = "ssf"
)
ss

2026/01/12 13:28:57 GWASLab v4.0.3 https://cloufield.github.io/gwaslab/
2026/01/12 13:28:57 (C) 2022-2026, Yunye He, Kamatani Lab, GPL-3.0 license, gwaslab@gmail.com
2026/01/12 13:28:57 Python version: 3.12.12 | packaged by conda-forge | (main, Oct 22 2025, 23:25:55) [GCC 14.3.0]
2026/01/12 13:28:57 Start to load format from formatbook....
2026/01/12 13:28:57  -ssf format meta info:
2026/01/12 13:28:57   - format_name  : ssf
2026/01/12 13:28:57   - format_source  : https://www.biorxiv.org/content/10.1101/2022.07.15.500230v1.full
2026/01/12 13:28:57   - format_cite_name  : GWAS-SSF v0.1
2026/01/12 13:28:57   - format_separator  : \t
2026/01/12 13:28:57   - format_na  : #NA
2026/01/12 13:28:57   - format_col_order  : chromosome,base_pair_location,effect_allele,other_allele,beta,odds_ratio,hazard_ratio,standard_error,effect_allele_frequency,p_value,neg_log_10_p_value,ci_upper,ci_lower,rsid,variant_id,info,ref_allele,n
2026/01/12 13:28:57   - format_version  :  20230328
2026/01/12 13:28:57  -ssf to gwaslab format dictionary:
2026/01/12 13:28:57   - ssf keys: variant_id,rsid,chromosome,base_pair_location,other_allele,effect_allele,effect_allele_frequency,n,beta,standard_error,p_value,neg_log_10_p_value,info,odds_ratio,hazard_ratio,ci_lower,ci_upper
2026/01/12 13:28:57   - gwaslab values: SNPID,rsID,CHR,POS,NEA,EA,EAF,N,BETA,SE,P,MLOG10P,INFO,OR,HR,OR_95L,OR_95U
2026/01/12 13:28:57 Start to initialize gl.Sumstats from file :/work/GCST90691576.tsv.gz
2026/01/12 13:29:19  -Reading columns          : other_allele,beta,effect_allele,neg_log_10_p_value,chromosome,base_pair_location,effect_allele_frequency,standard_error
2026/01/12 13:29:19  -Renaming columns to      : NEA,BETA,EA,MLOG10P,CHR,POS,EAF,SE
2026/01/12 13:29:19  -Current Dataframe shape : 23861759  x  8
2026/01/12 13:29:19  -Initiating a status column: STATUS ...
2026/01/12 13:29:19 #WARNING! Version of genomic coordinates is unknown for homo sapiens (build: 99)...
2026/01/12 13:29:20 Start to reorder the columns ...(v4.0.3)
2026/01/12 13:29:20  -Reordering columns to    : CHR,POS,EA,NEA,STATUS,EAF,BETA,SE,MLOG10P
2026/01/12 13:29:20 Finished reordering the columns.
2026/01/12 13:29:20  -Trying to convert datatype for CHR: string -> Int64...Success
2026/01/12 13:30:01  -No rsID/SNPID found; created SNPID from CHR:POS[:NEA:EA]
2026/01/12 13:30:01  -Column  : CHR   POS   EA       NEA      STATUS EAF     BETA    SE      MLOG10P SNPID
2026/01/12 13:30:01  -DType   : Int64 int64 category category int64  float64 float64 float64 float64 string
2026/01/12 13:30:01  -Verified: T     T     T        T        T      T       T       T       T       T
2026/01/12 13:30:02  -Current Dataframe memory usage: 1665.23 MB
2026/01/12 13:30:02 Finished loading data successfully!

### Map SNP ids to genes

https://cloufield.github.io/GWASTutorial/09_Gene_based_analysis/#magma-introduction
https://github.com/martinjzhang/scDRS/issues/2

First, we use ancestry-specific g1000_*.bim files from the 1000 Genomes Project (phase 3) reference panel to define the genomic positions of known SNPs and assign them to genes. SNPs located within 10 kb upstream or downstream of a gene are assigned to that gene, using gene coordinates from the NCBI gene location reference. Ancestry-specific reference files are used to ensure consistency between the SNP set and the linkage disequilibrium (LD) structure used in downstream analyses.

Second, we perform a gene-based association test to evaluate whether the combined GWAS signal of SNPs assigned to each gene is significantly stronger than expected by chance. Only SNPs present in both the GWAS summary statistics and the ancestry-matched reference panel are included in the analysis. This step uses ancestry-matched reference genotypes to account for linkage disequilibrium (LD), which arises when nearby SNPs are correlated due to co-inheritance. Correcting for LD prevents correlated SNPs from being treated as independent signals, which would would otherwise inflate gene-level test statistics and deflate p-values.

- SNPs are mapped to genes based on genomic position
- GWAS p-values are converted to SNP Z-scores
- SNPs within each gene are tested jointly
- LD between SNPs is modeled using a reference panel
- Output is one Z-score and p-value per gene

In [ ]:
# Install magma first
# mkdir MAGMA
# cd MAGMA
# wget https://ctg.cncr.nl/software/MAGMA/prog/magma_v1.10.zip
# unzip magma_v1.10.zip

In [ ]:
# Run in terminal
# !/work/islet_cartography_scrna/scripts/gwas/AB_annotate_sumstats.sh

#### Create a .gs file, top 1000 genes associated with traits

In [ ]:
# run in terminal
# !/work/islet_cartography_scrna/scripts/gwas/AC_create_gs_file_for_scdrs.sh

In [ ]:
# https://martinjzhang.github.io/scDRS/notebooks/quickstart.html

#### Other sumstat files from ldsc

Data from: Source: https://zenodo.org/records/10515792 (access: 08-01-2026)

Citation: https://www.nature.com/articles/s41598-025-32329-8

In [2]:
# Run in terminal
!wget https://zenodo.org/api/records/10515792/files/sumstats.tgz/content -O /work/islet_cartography_scrna/data/gwas/sumstats/sldsc_sumstats.tgz
!tar xvf /work/islet_cartography_scrna/data/gwas/sumstats/sldsc_sumstats.tgz

--2026-01-08 14:57:22--  https://zenodo.org/api/records/10515792/files/sumstats.tgz/content
Resolving zenodo.org (zenodo.org)... 188.185.48.75, 137.138.52.235, 188.185.43.153, ...
Connecting to zenodo.org (zenodo.org)|188.185.48.75|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2229052948 (2.1G) [application/octet-stream]
Saving to: ‘/work/islet_cartography_scrna/data/gwas/sumstats/sldsc_sumstats.tgz’

/work/islet_cartogr   1%[                    ]  23.99M  1.30MB/s    in 19s

2026-01-08 14:57:43 (1.24 MB/s) - Connection closed at byte 25155080. Retrying.

--2026-01-08 14:57:44--  (try: 2)  https://zenodo.org/api/records/10515792/files/sumstats.tgz/content
Connecting to zenodo.org (zenodo.org)|188.185.48.75|:443... connected.
HTTP request sent, awaiting response... 206 PARTIAL_CONTENT
Length: 2229052948 (2.1G), 2203897868 (2.1G) remaining [application/octet-stream]
Saving to: ‘/work/islet_cartography_scrna/data/gwas/sumstats/sldsc_sumstats.tgz’

/work/islet_cartogr 100%[===================>]   2.08G  1.21MB/s    in 27m 45s

2026-01-08 15:25:33 (1.26 MB/s) - ‘/work/islet_cartography_scrna/data/gwas/sumstats/sldsc_sumstats.tgz’ saved [2229052948/2229052948]

sumstats/
sumstats/UKB_460K.pigment_HAIR.sumstats.gz
sumstats/UKB_460K.disease_RESPIRATORY_ENT.sumstats.gz
sumstats/PASS_ENIGMA2_MeanPutamen.sumstats.gz
sumstats/PASS_SmokingInitiation_Liu2019.sumstats.gz
sumstats/UKB_460K.lung_FVCzSMOKE.sumstats.gz
sumstats/UKB_460K.body_LEFT_HANDED.sumstats.gz
sumstats/UKB_460K.cov_SMOKING_STATUS.sumstats.gz
sumstats/UKB_460K.biochemistry_LipoproteinA.sumstats.gz
sumstats/PASS_AdultOnsetAsthma_Ferreira2019.sumstats.gz
sumstats/UKB_460K.blood_EOSINOPHIL_COUNT.sumstats.gz
sumstats/PASS_SmallVesselStroke_Malik2018.sumstats.gz
sumstats/PASS_BipolarDisorder_Ruderfer2018.sumstats.gz
sumstats/PASS_BDSCZ_Ruderfer2018.sumstats.gz
sumstats/PASS_AtrialFibrillation_Nielsen2018.sumstats.gz
sumstats/PASS_Crohns_Disease.sumstats.gz
sumstats/PASS_MedicationUse_Wu2019.sumstats.gz
sumstats/UKB_460K.biochemistry_HDLcholesterol.sumstats.gz
sumstats/PASS_DrinksPerWeek_Liu2019.sumstats.gz
sumstats/PASS_Height1.sumstats.gz
sumstats/PASS_BIP_Stahl2019.sumstats.gz
sumstats/UKB_460K.body_BMIz.sumstats.gz
sumstats/UKB_460K.biochemistry_Phosphate.sumstats.gz
sumstats/UKB_460K.pigment_TANNING.sumstats.gz
sumstats/PASS_ShortSleepDuration_Dashti2019.sumstats.gz
sumstats/PASS_Intelligence_SavageJansen2018.sumstats.gz
sumstats/UKB_460K.biochemistry_AlkalinePhosphatase.sumstats.gz
sumstats/UKB_460K.other_MORNINGPERSON.sumstats.gz
sumstats/UKB_460K.biochemistry_Triglycerides.sumstats.gz
sumstats/PASS_IBD_deLange2017.sumstats.gz
sumstats/PASS_OvarianCancer.sumstats.gz
sumstats/PASS_UC_deLange2017.sumstats.gz
sumstats/UKB_460K.biochemistry_TotalBilirubin.sumstats.gz
sumstats/UKB_460K.pigment_SKIN.sumstats.gz
sumstats/PASS_Parkinsons_23andMe_Corces2020.sumstats.gz
sumstats/PASS_Triglycerides.sumstats.gz
sumstats/UKB_460K.blood_LYMPHOCYTE_COUNT.sumstats.gz
sumstats/UKB_460K.biochemistry_Glucose.sumstats.gz
sumstats/PASS_Stroke_Malik2018.sumstats.gz
sumstats/PASS_IschemicStroke_Malik2018.sumstats.gz
sumstats/PASS_CigarettesPerDay_Liu2019.sumstats.gz
sumstats/PASS_BreastCancer.sumstats.gz
sumstats/PASS_FastingGlucose_Manning.sumstats.gz
sumstats/PASS_SmokingCessation_Liu2019.sumstats.gz
sumstats/UKB_460K.body_HEIGHTz.sumstats.gz
sumstats/PASS_MDD_Howard2019.sumstats.gz
sumstats/UKB_460K.body_WHRadjBMIz.sumstats.gz
sumstats/UKB_460K.biochemistry_DirectBilirubin.sumstats.gz
sumstats/PASS_CardioembolicStroke_Malik2018.sumstats.gz
sumstats/UKB_460K.repro_NumberChildrenEverBorn_Male.sumstats.gz
sumstats/UKB_460K.body_BALDING4.sumstats.gz
sumstats/UKB_460K.disease_ASTHMA_DIAGNOSED.sumstats.gz
sumstats/PASS_Autism.sumstats.gz
sumstats/PASS_Worry_Nagel2018.sumstats.gz
sumstats/UKB_460K.biochemistry_AspartateAminotransferase.sumstats.gz
sumstats/UKB_460K.pigment_HAIR_darkbrown.sumstats.gz
sumstats/PASS_Alzheimers_Jansen2019.sumstats.gz
sumstats/UKB_460K.disease_HYPERTENSION_DIAGNOSED.sumstats.gz
sumstats/UKB_460K.repro_MENARCHE_AGE.sumstats.gz
sumstats/PASS_Multiple_sclerosis.sumstats.gz
sumstats/PASS_LongSleepDuration_Dashti2019.sumstats.gz
sumstats/PASS_Lupus.sumstats.gz
sumstats/UKB_460K.body_BALDING1.sumstats.gz
sumstats/PASS_AlzheimersProxy_Marioni2018.sumstats.gz
sumstats/PASS_AgeOfInitiation_Liu2019.sumstats.gz
sumstats/PASS_Bone_Mineral_Density_Kemp_2017.sumstats.gz
sumstats/PASS_HbA1C.sumstats.gz
sumstats/PASS_MDD_Wray2018.sumstats.gz
sumstats/UKB_460K.cov_EDU_COLLEGE.sumstats.gz
sumstats/UKB_460K.repro_NumberChildrenEverBorn_Female.sumstats.gz
sumstats/UKB_460K.pigment_HAIR_blackmale.sumstats.gz
sumstats/PASS_Bipolar_Disorder.sumstats.gz
sumstats/UKB_460K.cancer_PROSTATE.sumstats.gz
sumstats/PASS_DepressedAffect_Nagel2018.sumstats.gz
sumstats/UKB_460K.disease_ALLERGY_ECZEMA_DIAGNOSED.sumstats.gz
sumstats/UKB_460K.biochemistry_Calcium.sumstats.gz
sumstats/PASS_Alzheimer.sumstats.gz
sumstats/UKB_460K.biochemistry_Albumin.sumstats.gz
sumstats/UKB_460K.biochemistry_HbA1c.sumstats.gz
sumstats/PASS_Menarche2017.sumstats.gz
sumstats/PASS_Years_of_Education2.sumstats.gz
sumstats/UKB_460K.biochemistry_Creatinine.sumstats.gz
sumstats/PASS_GeneralRiskTolerance_KarlssonLinner2019.sumstats.gz
sumstats/UKB_460K.repro_AgeFirstBirth_Female.sumstats.gz
sumstats/UKB_460K.biochemistry_Urate.sumstats.gz
sumstats/UKB_460K.biochemistry_GammaGlutamyltransferase.sumstats.gz
sumstats/UKB_460K.blood_MEAN_PLATELET_VOL.sumstats.gz
sumstats/UKB_460K.blood_PLATELET_COUNT.sumstats.gz
sumstats/PASS_AlzheimersPaternal_Marioni2018.sumstats.gz
sumstats/UKB_460K.biochemistry_Testosterone_Male.sumstats.gz
sumstats/UKB_460K.cancer_ALL.sumstats.gz
sumstats/PASS_FetalBirthWeight_Warrington2019.sumstats.gz
sumstats/PASS_Ever_Smoked.sumstats.gz
sumstats/UKB_460K.biochemistry_Cholesterol.sumstats.gz
sumstats/UKB_460K.biochemistry_TotalProtein.sumstats.gz
sumstats/UKB_460K.pigment_HAIR_blonde.sumstats.gz
sumstats/UKB_460K.bp_DIASTOLICadjMEDz.sumstats.gz
sumstats/UKB_460K.disease_ENDOCRINE_DIABETES.sumstats.gz
sumstats/UKB_460K.biochemistry_CreactiveProtein.sumstats.gz
sumstats/UKB_460K.biochemistry_LDLdirect.sumstats.gz
sumstats/UKB_460K.mental_NEUROTICISM.sumstats.gz
sumstats/UKB_460K.disease_DERMATOLOGY.sumstats.gz
sumstats/PASS_AnorexiaNervosa_Duncan_2017.sumstats.gz
sumstats/UKB_460K.cov_EDU_YEARS.sumstats.gz
sumstats/PASS_ChildOnsetAsthma_Ferreira2019.sumstats.gz
sumstats/UKB_460K.repro_NumberChildrenEverBorn_Pooled.sumstats.gz
sumstats/UKB_460K.bmd_HEEL_TSCOREz.sumstats.gz
sumstats/PASS_Primary_biliary_cirrhosis.sumstats.gz
sumstats/PASS_Schizophrenia.sumstats.gz
sumstats/PASS_Type_2_Diabetes.sumstats.gz
sumstats/PASS_Depression_Nagel2018.sumstats.gz
sumstats/UKB_460K.impedance_BASAL_METABOLIC_RATEz.sumstats.gz
sumstats/UKB_460K.cancer_BREAST.sumstats.gz
sumstats/PASS_LDL.sumstats.gz
sumstats/PASS_MaternalBirthWeight_Warrington2019.sumstats.gz
sumstats/PASS_Anorexia.sumstats.gz
sumstats/UKB_460K.blood_RBC_DISTRIB_WIDTH.sumstats.gz
sumstats/PASS_NumberChildrenEverBorn.sumstats.gz
sumstats/UKB_460K.disease_AID_ALL.sumstats.gz
sumstats/PASS_Neuroticism_Nagel2018.sumstats.gz
sumstats/PASS_Celiac.sumstats.gz
sumstats/PASS_Insomnia_Jansen2019.sumstats.gz
sumstats/PASS_Coronary_Artery_Disease_Howson_2017.sumstats.gz
sumstats/UKB_460K.biochemistry_VitaminD.sumstats.gz
sumstats/PASS_IBD.sumstats.gz
sumstats/PASS_ADHD_Demontis2018.sumstats.gz
sumstats/UKB_460K.disease_HI_CHOL_SELF_REP.sumstats.gz
sumstats/PASS_Autism_Grove2019.sumstats.gz
sumstats/UKB_460K.biochemistry_Urea.sumstats.gz
sumstats/UKB_460K.disease_THYROID_ANY_SELF_REP.sumstats.gz
sumstats/UKB_460K.biochemistry_CystatinC.sumstats.gz
sumstats/UKB_460K.blood_MONOCYTE_COUNT.sumstats.gz
sumstats/PASS_Epilepsy_Anney_2014.sumstats.gz
sumstats/UKB_460K.cancer_MELANOMA.sumstats.gz
sumstats/PASS_SleepDuration_Dashti2019.sumstats.gz
sumstats/PASS_Type_1_Diabetes.sumstats.gz
sumstats/PASS_CD_deLange2017.sumstats.gz
sumstats/PASS_SCZvsBD_Ruderfer2018.sumstats.gz
sumstats/PASS_ProstateCancer.sumstats.gz
sumstats/UKB_460K.blood_WHITE_COUNT.sumstats.gz
sumstats/UKB_460K.bp_SYSTOLICadjMEDz.sumstats.gz
sumstats/PASS_Rheumatoid_Arthritis.sumstats.gz
sumstats/UKB_460K.disease_AID_SURE.sumstats.gz
sumstats/UKB_460K.biochemistry_IGF1.sumstats.gz
sumstats/PASS_Coronary_Artery_Disease.sumstats.gz
sumstats/PASS_BMI1.sumstats.gz
sumstats/PASS_Neuroticism.sumstats.gz
sumstats/UKB_460K.disease_DIABETES_ANY_DIAGNOSED.sumstats.gz
sumstats/PASS_Ulcerative_Colitis.sumstats.gz
sumstats/PASS_VerbalNumericReasoning_Davies2018.sumstats.gz
sumstats/PASS_HDL.sumstats.gz
sumstats/UKB_460K.blood_PLATELET_DISTRIB_WIDTH.sumstats.gz
sumstats/UKB_460K.blood_MEAN_SPHERED_CELL_VOL.sumstats.gz
sumstats/UKB_460K.disease_HYPOTHYROIDISM_SELF_REP.sumstats.gz
sumstats/UKB_460K.biochemistry_SHBG.sumstats.gz
sumstats/UKB_460K.blood_HIGH_LIGHT_SCATTER_RETICULOCYTE_COUNT.sumstats.gz
sumstats/UKB_460K.biochemistry_AlanineAminotransferase.sumstats.gz
sumstats/PASS_SWB.sumstats.gz
sumstats/PASS_Lean_Body_Mass_Zillikens_2017.sumstats.gz
sumstats/UKB_460K.biochemistry_ApolipoproteinB.sumstats.gz
sumstats/PASS_Schizophrenia_Pardinas2018.sumstats.gz
sumstats/UKB_460K.disease_PSORIASIS.sumstats.gz
sumstats/UKB_460K.biochemistry_ApolipoproteinA.sumstats.gz
sumstats/UKB_460K.disease_CARDIOVASCULAR.sumstats.gz
sumstats/UKB_460K.blood_RED_COUNT.sumstats.gz
sumstats/PASS_AlzheimersMaternal_Marioni2018.sumstats.gz
sumstats/PASS_Schizophrenia_Ruderfer2018.sumstats.gz
sumstats/UKB_460K.pigment_SUNBURN.sumstats.gz
sumstats/UKB_460K.lung_FEV1FVCzSMOKE.sumstats.gz
sumstats/PASS_Years_of_Education1.sumstats.gz
sumstats/UKB_460K.repro_MENOPAUSE_AGE.sumstats.gz
sumstats/PASS_DS.sumstats.gz
sumstats/PASS_LargeArteryStroke_Malik2018.sumstats.gz
sumstats/UKB_460K.disease_T2D.sumstats.gz
sumstats/UKB_460K.blood_MEAN_CORPUSCULAR_HEMOGLOBIN.sumstats.gz
sumstats/PASS_ReactionTime_Davies2018.sumstats.gz
sumstats/PASS_AgeFirstBirth.sumstats.gz